#2025.02.05自用规则，交易所
#!name=Cryptocurrency


[Rule]
DOMAIN-SUFFIX,appsflayer.com,DIRECT #币安
DOMAIN-SUFFIX,binance.cloud,DIRECT #币安
DOMAIN-SUFFIX,binance.com,DIRECT #币安
DOMAIN-SUFFIX,binance.me,DIRECT #币安
DOMAIN-SUFFIX,binancecnt.com,DIRECT #币安
DOMAIN-SUFFIX,binancefuture.com,DIRECT #币安
DOMAIN-SUFFIX,bnappzh.co,DIRECT #币安
DOMAIN-SUFFIX,bnbstatic.com,DIRECT #币安
DOMAIN-SUFFIX,bnbzh.ac,DIRECT #币安
DOMAIN-SUFFIX,bntrace.com,DIRECT #币安
DOMAIN-SUFFIX,saasexch.cc,DIRECT #币安
DOMAIN-SUFFIX,saasexch.com,DIRECT #币安
DOMAIN-SUFFIX,binance.info,DIRECT #币安
DOMAIN-KEYWORD,binance,DIRECT #币安
DOMAIN-KEYWORD,saasexch,DIRECT #币安
DOMAIN-KEYWORD,yingwangtech,DIRECT #币安
DOMAIN-SUFFIX,okex.com,DIRECT #欧易
DOMAIN-SUFFIX,oklink.com,DIRECT #欧易
DOMAIN-SUFFIX,okx.com,DIRECT #欧易
DOMAIN-SUFFIX,gate.io,DIRECT #芝麻开门
DOMAIN-SUFFIX,gateio.services,DIRECT #芝麻开门
DOMAIN-SUFFIX,gateimg.com,DIRECT #芝麻开门
DOMAIN-SUFFIX,gatedataimg.com,DIRECT #芝麻开门
DOMAIN-SUFFIX,gateweb3.cc,DIRECT #芝麻开门
DOMAIN-SUFFIX,zhaqby.com,DIRECT #芝麻开门
DOMAIN-KEYWORD,bybit,DIRECT #bybit交易所
DOMAIN,bybit-exchange.github.io,DIRECT       #bybit交易所
DOMAIN,bybit.ada.support,DIRECT      #bybit交易所
DOMAIN-SUFFIX,bybit.com,DIRECT       #bybit交易所
DOMAIN-SUFFIX,bycsi.com,DIRECT       #bybit交易所
DOMAIN-SUFFIX,bytick.com,DIRECT      #bybit交易所
DOMAIN-SUFFIX,byapis.com,DIRECT      #bybit交易所
DOMAIN-SUFFIX,bycbe.com,DIRECT       #bybit交易所
DOMAIN-SUFFIX,bymj.io,DIRECT         #bybit交易所
DOMAIN-SUFFIX,byabcde.com,DIRECT     #bybit交易所
DOMAIN-SUFFIX,byapps.net,DIRECT      #bybit交易所
DOMAIN-SUFFIX,byd3c3.com,DIRECT      #bybit交易所
DOMAIN-SUFFIX,bybit.biz,DIRECT       #bybit交易所
DOMAIN-SUFFIX,bybdc6.com,DIRECT     #bybit交易所
DOMAIN-SUFFIX,bybit-global.com,DIRECT   #bybit交易所
DOMAIN-SUFFIX,bybit.cloud,DIRECT        #bybit交易所
